okta:
  oauth2:
    issuer: https://dev-29553022.okta.com/oauth2/default
    audience: api://default
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    scopes: openid, profile, email, offline_access
    post-logout-redirect-uri: http://localhost:9090

server:
  port: 9090