version: '3.7'
services:
  mysql:
    image: mysql:latest
    ports:
      - 5445:3306
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE=easybank
      - MYSQL_USER=rakib
      - MYSQL_PASSWORD=Rakib09
    volumes:
      - easy-mysql-db-volume:/var/lib/mysql

volumes:
  easy-mysql-db-volume:
